### ISSUE TITLE
Redirection to NAMUG points to Modelica.org

### ISSUE THREAD

**Issue by lvanfretti** [modelica/AmericanModelicaConference2020#1]
@ManuelNvro at the bottom of the pages there is the logo of NAMUG, if you click on it, it re-directs to modelica.org instead of: [https://namug.org/](https://namug.org/) can you fix that?
Thank you!
Luigi
![Screen Shot 2020-10-31 at 12 07 37 PM](https://user-images.githubusercontent.com/7248948/97784000-d0025400-1b71-11eb-84a6-f98b7254c193.png)

**Comment by ManuelNvro** [comment]
Fixed!
